{{ $ns := .Release.Namespace }}
{{ $sa := .Values.ServiceAccount }}
{{- if .Values.thanos.query.enabled }}
{{- range .Values.thanos.query.serviceDiscoveryFileConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ . }}
  namespace: {{ $ns }}
  labels:
    app: {{ include "thanos.name" $ }}
    chart: {{ include "thanos.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
data:
  stores.yaml: |-
    - targets: []
{{- end }}
{{- end }}