{{ $thanosCa := genCA "Thanos CA" 3650 }}
{{ $thanosServer := genSignedCert "server.thanos.localhost.localdomain" nil nil 3650 $thanosCa }}
{{ $thanosClient := genSignedCert "client.thanos.localhost.localdomain" nil nil 3650 $thanosCa }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos-client-tls
  labels:
    app: {{ include "thanos.name" $ }}
    chart: {{ include "thanos.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
data:
  tls.crt: {{ b64enc $thanosClient.Cert }}
  tls.key: {{ b64enc $thanosClient.Key }}
  ca.crt: {{ b64enc $thanosCa.Cert }} 
---

