# Internal address for the cluster's Thanos gRPC service.
# thanosAddress: "HOST:PORT"
thanosAddress: ""
# Service account used to delete Thanos store configmaps
ServiceAccount: thanos-kubeaddons

thanos:
  store:
    enabled: false
  compact:
    enabled: false
  bucket:
    enabled: false
  sidecar:
    enabled: false

  query:
    # Name of HTTP request header used for dynamic prefixing of UI links and redirects.
    webPrefixHeader: "X-Forwarded-Prefix"
    # Enable DNS discovery for stores
    storeDNSDiscovery: false
    # Enable DNS discovery for sidecars (this is for the chart built-in sidecar service)
    sidecarDNSDiscovery: false
    # Addresses of statically configured store API servers (repeatable).
    stores: []
    # Names of configmaps that contain addresses of store API servers, used for file service discovery.
    serviceDiscoveryFileConfigMaps:
    - thanos-query-stores
    # Refresh interval to re-read file SD files. It is used as a resync fallback.
    serviceDiscoveryInterval: 5m
    # Add extra arguments to the compact service
    extraArgs:
    certSecretName: thanos-client-tls
    http:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          traefik.frontend.rule.type: "PathPrefixStrip"
          traefik.ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User"
          traefik.ingress.kubernetes.io/auth-type: "forward"
          traefik.ingress.kubernetes.io/auth-url: "http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/"
          traefik.ingress.kubernetes.io/priority: "2"
        path: "/ops/portal/kubeaddons/monitoring/query"
        hosts:
          - ""
        tls: []
